### ISSUE TITLE
Can this library work as Plugin Loader?

### ISSUE THREAD

**Issue by aloksharma1** [John0King/LazyMan.ModularLoader#3]
Hello,

Instead of Modules i want my assembly subparts to behave as plugins, load/unload on runtime without affecting host app. Can you guide me how this is possible with this library, currently i am using [DotnetCorePlugins](https://github.com/natemcmaster/DotNetCorePlugins)
but this have bug in razor that your library solves, so i am interested if i can port to yours.

thanks

**Comment by John0King** [comment]
> Can this library work as Plugin Loader

yes,  but you may want to use `DotnetCorePlugins` because this project is in slow development and for reseach purpose currently (no officol release on nuget.org)

> but this have bug in razor that your library solves

well, there are only two ways to acrchve plugins, 1). `Assembly.Load`  and use `MemeoryStream` or `byte[]`  2)  `AssemblyLoadContext` aka  `ALC`.  the problem that razor happed is that the razor is load to `Default` ALC in "hard code" way (ps:  .net 6 + Source Generator should fixed this because now the razor files are generat .g.cs  in your project `obj` folder and there are no additional assembly need to be load).
and (for below .net 6 ) this project fix it in a very simple way ,  it add a fallback method to the default ALC and forward it to the plugin ALC.

https://github.com/John0King/LazyMan.ModularLoader/blob/cb805ed3dbdbe6c01f3d1a4439d1f1ace5261a69/test/SubAppTest/HostApp/Startup.cs#L47-L78

and that means  you can not make a razor dll's assembly name as same as other plugins (because the way that razor add to `Default ALC` is not compatiable with the "Plugin architecture" )

**Comment by John0King** [comment]
be notice that  unloadable ALC have many limit  as #1  meation ,
for example : 
- unloadable ALC must not use dynamic proxy
- all asp.net core assembly must in "plugin host"
- only work with "framework dependend publish"  (all because the 2nd issue,  you must very careful to not add any host used asembly in your plugin, otherwise the Type mismatch as I meation in https://github.com/dotnet/runtime/issues/37576)

and thats why this project no active develop.

**Comment by aloksharma1** [comment]
ok, so i will try to do this in net 6 but i am also ready to wait till net 7 if that's going to solve these issues that you have pointed out.
i am very careful about point 2 as all development follow one common project as reference assembly holder+host & plugin folders only use specific refernces when/if required and not available in main project.
